name: Reflections of a journey
favicon: null
layout_spectrum: 0.7702967112418264
typography_spectrum: 0.65425
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5279364062007517
  lightness: 0.8125
  saturation: 0.16668831440620124
  rhythmicContrast: 0.12852845108136535
purpose: []
